using System;
using System.IO;
using System.Linq;
using System.Windows;
using Microsoft.Win32;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using TuitionManagementSystem.Data;
using TuitionManagementSystem.Helpers;

namespace TuitionManagementSystem.ViewModels
{
    public class ReportsViewModel : ViewModelBase
    {
        public string Grade => AppSession.CurrentGrade;

        private DateTime _fromDate = DateTime.Today.AddDays(-7);
        public DateTime FromDate { get => _fromDate; set => SetField(ref _fromDate, value); }

        private DateTime _toDate = DateTime.Today;
        public DateTime ToDate { get => _toDate; set => SetField(ref _toDate, value); }

        private string _statusMessage;
        public string StatusMessage { get => _statusMessage; set => SetField(ref _statusMessage, value); }

        public RelayCommand ExportPendingFeesPdfCommand { get; }

        public ReportsViewModel()
        {
            QuestPDF.Settings.License = LicenseType.Community;
            ExportPendingFeesPdfCommand = new RelayCommand(_ => ExportPendingFeesPdf());
        }

        private void ExportPendingFeesPdf()
        {
            var records = DatabaseHelper.GetPendingFees(Grade, FromDate, ToDate, null);

            var dialog = new SaveFileDialog
            {
                Filter = "PDF file (*.pdf)|*.pdf",
                FileName = $"{Grade.Replace(" ", "")}_FeeReport_{DateTime.Now:yyyyMMdd}.pdf"
            };
            if (dialog.ShowDialog() != true) return;

            QuestPDF.Fluent.Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);
                    page.Header().Text($"{Grade} - Pending Fee Report ({FromDate:dd MMM yyyy} to {ToDate:dd MMM yyyy})")
                        .SemiBold().FontSize(16);

                    page.Content().PaddingTop(15).Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(2);
                            columns.RelativeColumn(2);
                            columns.RelativeColumn(2);
                            columns.RelativeColumn(2);
                            columns.RelativeColumn(2);
                        });

                        table.Header(header =>
                        {
                            header.Cell().Text("Student").SemiBold();
                            header.Cell().Text("Date").SemiBold();
                            header.Cell().Text("Lesson").SemiBold();
                            header.Cell().Text("Status").SemiBold();
                            header.Cell().Text("Amount Due").SemiBold();
                        });

                        foreach (var r in records)
                        {
                            var session = DatabaseHelper.GetSession(r.Grade, DateTime.Parse(r.SessionDate));
                            table.Cell().Text(r.StudentName);
                            table.Cell().Text(r.SessionDate);
                            table.Cell().Text(r.LessonName);
                            table.Cell().Text(r.FeeStatus);
                            table.Cell().Text($"Rs. {session?.DailyFee ?? 0:N0}");
                        }
                    });

                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.Span("Generated by Jayagath Institute Tuition Management System - ");
                        x.Span(DateTime.Now.ToString("dd MMM yyyy HH:mm"));
                    });
                });
            }).GeneratePdf(dialog.FileName);

            StatusMessage = $"Report exported to {dialog.FileName}";
            MessageBox.Show("PDF report generated successfully.", "Export complete",
                MessageBoxButton.OK, MessageBoxImage.Information);
        }
    }
}
